version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 2
    groups:
      all-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - '*'
      security-dependencies:
        applies-to: security-updates
        update-types:
          - minor
          - patch
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 2
    groups:
      all-actions:
        update-types:
          - minor
          - patch
        patterns:
          - '*'
